# Numpy Revision

In [1]:
import numpy as np

print(np.__version__)

1.23.5


In [3]:
q=np.arange(10)
q

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create an 3*3 matrix with all true values

In [8]:

fi=np.full((3,3), True, dtype=bool)
fi

re=np.ones((3,3), dtype=bool)
print(re)
print(fi)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
#extract all the odd numbers from the array

arr=np.arange(15)

a=arr[arr%2==1]
a


array([ 1,  3,  5,  7,  9, 11, 13])

In [11]:
# replace all the odd numbers with -1
arr=np.arange(15)
arr
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14])

In [12]:
# replace all the odd number with 'chinna', without changing the array

arr=np.arange(20)
f=np.where(arr%2==1, 'chinna', arr)
f

array(['0', 'chinna', '2', 'chinna', '4', 'chinna', '6', 'chinna', '8',
       'chinna', '10', 'chinna', '12', 'chinna', '14', 'chinna', '16',
       'chinna', '18', 'chinna'], dtype='<U11')

In [14]:
# convert 1dim, to 2dim with 2 rows
arr=np.arange(6)
arr

arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# how to stack arrays a nd b vertically and horizontally
from numpy import vstack
arr1=np.arange(10).reshape(2,5)
arr2=np.repeat(20, 10).reshape(2,5)
print(arr1)
print(arr2)

z=np.concatenate([arr1, arr2])
print(z)
# second method
q=np.vstack([arr1, arr2])
print(q)
# third method
a=np.r_[arr1, arr2]
print(a)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[20 20 20 20 20]
 [20 20 20 20 20]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 20 20 20 20]
 [20 20 20 20 20]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 20 20 20 20]
 [20 20 20 20 20]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [22]:
# Now for horizontally

b=np.concatenate([arr1, arr2], axis=1)
print(b)
# second method
c=np.hstack([arr1, arr2])
print(c)
# third method
d=np.c_[arr1, arr2]
print(d)

[[ 0  1  2  3  4 20 20 20 20 20]
 [ 5  6  7  8  9 20 20 20 20 20]]
[[ 0  1  2  3  4 20 20 20 20 20]
 [ 5  6  7  8  9 20 20 20 20 20]]
[[ 0  1  2  3  4 20 20 20 20 20]
 [ 5  6  7  8  9 20 20 20 20 20]]


In [27]:
# create a array like these arr=[1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3]

a=np.array([1,2,3])
b=np.repeat(a,3)
print(b)
c=np.tile(a,3)
print(c)
d=np.r_[b,c]
g=np.c_[b,c]
print(g)
print(d)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[[1 1]
 [1 2]
 [1 3]
 [2 1]
 [2 2]
 [2 3]
 [3 1]
 [3 2]
 [3 3]]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [29]:
# get the common items between the elements

a=np.array([1,2,5,6,7,8,9])
b=np.array([2,6,8,9,11,45,67])

c=np.intersect1d(a,b)
c

array([2, 6, 8, 9])

In [34]:
# from c remove all the items present in d

c=np.array([1,2,3,4,5])
d=np.array([3,2,5,6,7,8])
g=np.setdiff1d(c,d)
g

array([1, 4])

In [35]:
#get the positions where elements of c and d match
c=np.array([1,2,3,4,5,6])
d=np.array([3,2,5,6,7,8])
li8=np.where(c==d)
li8

(array([1], dtype=int64),)

In [48]:
# get all the elements between 5 and 10

a1=np.arange(15)

bn=np.where((a1>=5)&(a1<=10))
bn
new=a[(a>=5)&(a<=10)]
new
final=np.where(np.logical_and((a>=5),(a<=10)))
final

(array([2, 3, 4, 5, 6], dtype=int64),)

In [51]:
# create an fun max that handle two arrays

c=np.array([1,2,3,4,5,6])
d=np.array([3,2,5,6,7,8])

def maxx(c,d):
    if c>d:
        return c
    else:
        return d
pair_max=np.vectorize(maxx, otypes=[int])
pair_max(c,d)



array([3, 2, 5, 6, 7, 8])

In [56]:
# swap columns 1 nad 2 in the array

c=np.arange(9).reshape(3,3)
print(c)
d=c[:, (1,0,2)]
d

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [55]:
# swap rows 1 nad 2 in the array
e=c[(1,0,2), :]
e

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [57]:
# reverse the rows of a 2d array
g=c[::-1]
g

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [58]:
# reverse the colomns of a 2d array
f=c[:, ::-1]
f

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [59]:
# cretae a 2d aray of 5*3 of random decimals b/w 5 and 10

fine=np.random.uniform(5,10, size=(5,3))
fine

array([[5.75383997, 6.8115876 , 6.35127124],
       [6.53838637, 5.28978845, 9.93318412],
       [9.5283264 , 5.24263994, 6.55428805],
       [5.38856646, 7.10706555, 6.36326871],
       [5.95268111, 7.5527127 , 7.50125846]])